language: ruby
rvm:
  - 2.4.1
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

script: scripts/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
